spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb
    username: rent
    password: admin
    initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
